name: an_ml_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.6
  - numpy=1.21.2
  - pandas=1.3.3
  - scipy=1.7.1
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - scikit-learn=0.24.2
  - xgboost=1.5.0
  - lightgbm=3.3.0
  - imbalanced-learn=0.8.0
  - category_encoders=2.3.0
  - pyyaml=5.4.1
  - joblib=1.0.1
  - threadpoolctl=2.2.0